"""
Pydantic Models and Schemas for AI Meeting Intelligence System

This module defines all data models used throughout the application,
ensuring type safety and validation for all data structures.
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class MessageRole(str, Enum):
    """Role of a message in the conversation."""
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class TranscriptSegment(BaseModel):
    """A single segment of a meeting transcript."""
    
    speaker: str = Field(
        description="Name or identifier of the speaker",
    )
    timestamp: str = Field(
        description="Timestamp of the segment (e.g., '00:05:23')",
    )
    text: str = Field(
        description="The spoken text content",
    )
    start_seconds: Optional[float] = Field(
        default=None,
        description="Start time in seconds",
    )
    end_seconds: Optional[float] = Field(
        default=None,
        description="End time in seconds",
    )


class Meeting(BaseModel):
    """A complete meeting with metadata and transcript."""
    
    id: str = Field(
        description="Unique identifier for the meeting",
    )
    title: str = Field(
        description="Title or subject of the meeting",
    )
    date: Optional[datetime] = Field(
        default=None,
        description="Date and time of the meeting",
    )
    participants: list[str] = Field(
        default_factory=list,
        description="List of meeting participants",
    )
    segments: list[TranscriptSegment] = Field(
        default_factory=list,
        description="Transcript segments",
    )
    raw_transcript: str = Field(
        default="",
        description="Raw transcript text",
    )
    source_file: Optional[str] = Field(
        default=None,
        description="Original source file name",
    )


class ActionItem(BaseModel):
    """An action item extracted from a meeting."""
    
    task: str = Field(
        description="Description of the task",
    )
    owner: Optional[str] = Field(
        default=None,
        description="Person responsible for the task",
    )
    deadline: Optional[str] = Field(
        default=None,
        description="Deadline or due date (if mentioned)",
    )
    priority: Optional[str] = Field(
        default=None,
        description="Priority level (high, medium, low)",
    )
    context: Optional[str] = Field(
        default=None,
        description="Context or source from the transcript",
    )


class Decision(BaseModel):
    """A decision made during the meeting."""
    
    decision: str = Field(
        description="Description of the decision",
    )
    made_by: Optional[str] = Field(
        default=None,
        description="Person who made or announced the decision",
    )
    context: Optional[str] = Field(
        default=None,
        description="Context or reasoning behind the decision",
    )
    related_discussion: Optional[str] = Field(
        default=None,
        description="Related discussion points",
    )


class MeetingSummary(BaseModel):
    """Summary of a meeting generated by the AI."""
    
    overview: str = Field(
        description="High-level overview of the meeting",
    )
    key_topics: list[str] = Field(
        default_factory=list,
        description="Main topics discussed",
    )
    decisions: list[Decision] = Field(
        default_factory=list,
        description="Key decisions made",
    )
    action_items: list[ActionItem] = Field(
        default_factory=list,
        description="Action items identified",
    )
    participants_summary: dict[str, str] = Field(
        default_factory=dict,
        description="Summary of each participant's contributions",
    )


class ChatMessage(BaseModel):
    """A message in the chat conversation."""
    
    role: MessageRole = Field(
        description="Role of the message sender",
    )
    content: str = Field(
        description="Content of the message",
    )
    timestamp: datetime = Field(
        default_factory=datetime.now,
        description="Timestamp of the message",
    )


class ChatRequest(BaseModel):
    """Request to chat with the AI about a meeting."""
    
    meeting_id: str = Field(
        description="ID of the meeting to query",
    )
    question: str = Field(
        description="User's question about the meeting",
    )
    chat_history: list[ChatMessage] = Field(
        default_factory=list,
        description="Previous messages in the conversation",
    )


class ChatResponse(BaseModel):
    """Response from the AI chat."""
    
    answer: str = Field(
        description="AI's answer to the question",
    )
    sources: list[str] = Field(
        default_factory=list,
        description="Source excerpts from the transcript",
    )
    confidence: Optional[float] = Field(
        default=None,
        description="Confidence score of the answer",
    )


class TranscriptUploadResponse(BaseModel):
    """Response after uploading a transcript."""
    
    meeting_id: str = Field(
        description="ID assigned to the meeting",
    )
    title: str = Field(
        description="Detected or assigned title",
    )
    segment_count: int = Field(
        description="Number of transcript segments",
    )
    participant_count: int = Field(
        description="Number of unique participants",
    )
    message: str = Field(
        description="Status message",
    )


class AudioTranscriptionRequest(BaseModel):
    """Request to transcribe an audio file."""
    
    language: Optional[str] = Field(
        default=None,
        description="Language code (e.g., 'en', 'es'). Auto-detect if None.",
    )


class AudioTranscriptionResponse(BaseModel):
    """Response after transcribing audio."""
    
    meeting_id: str = Field(
        description="ID assigned to the meeting",
    )
    transcript: str = Field(
        description="Full transcript text",
    )
    segments: list[TranscriptSegment] = Field(
        description="Transcript segments with timestamps",
    )
    language: str = Field(
        description="Detected language",
    )
    duration_seconds: float = Field(
        description="Duration of the audio in seconds",
    )


class AnalysisRequest(BaseModel):
    """Request to analyze a meeting transcript."""
    
    meeting_id: str = Field(
        description="ID of the meeting to analyze",
    )
    include_summary: bool = Field(
        default=True,
        description="Include meeting summary",
    )
    include_decisions: bool = Field(
        default=True,
        description="Extract decisions",
    )
    include_action_items: bool = Field(
        default=True,
        description="Extract action items",
    )


class AnalysisResponse(BaseModel):
    """Response with meeting analysis results."""
    
    meeting_id: str = Field(
        description="ID of the analyzed meeting",
    )
    summary: Optional[MeetingSummary] = Field(
        default=None,
        description="Meeting summary",
    )
    processing_time_seconds: float = Field(
        description="Time taken to process",
    )
